// Retain's copy, lifted out of the view so the file stays under its size
// ceiling. Same `{ en, "pt-BR" }` shape every surface uses — `RetainView` and
// the done-for-today surface both read it through `useT`.

export const STRINGS = {
  en: {
    map: "← Map",
    thisNode: "This node",
    retainReview: "Retain · Review",
    doneForToday: "Done for today",
    queueClear: "Queue clear. You ended on a green node.",
    finishedBody:
      "Short, winnable, and it lit something up — the feeling that pulls you back tomorrow. FSRS has already scheduled every card for its next optimal moment.",
    litUpToday: (labels: string) => `Lit up today · ${labels}`,
    dayStreak: "day streak",
    todayIn: "today, in",
    nodesAlive: "nodes alive",
    freezesBanked: (n: number) =>
      `${n} freeze${n === 1 ? "" : "s"} banked — miss a day and the streak still holds.`,
    backToMap: "Back to the map →",
    autoGenerated: (source: string) => `auto-generated · from your ${source} session`,
    beforeFlip: "Before you flip · how solid is this?",
    answer: "Answer",
    explainAside: "Explain · micro-Socratic aside",
    gradeInterval: "Grade · sets the next interval (FSRS)",
    confidenceVsResult: "Confidence vs. result",
    failedReexplainLead:
      "A failed card doesn’t just reschedule — a 30-second Socratic re-explanation, right here:",
    nodeFlaggedShaky: (nodeLabel: string) => `“${nodeLabel}” flagged Shaky on your map.`,
    retentionFailureBody:
      "Retention failure re-enters the loop — the node pulls attention back until it’s re-taught. This is what separates the app from Anki plus a chatbot.",
    reteachNow: "Re-teach now →",
    scheduleReteach: "Schedule re-teach · continue",
    todaysBudget: "Today’s budget",
    dailyTarget: (min: number) => `Daily target · ${min} min`,
    budgetBody:
      "Framed in minutes, never a wall of cards. When the target’s met, you’re done — guilt-free.",
    retentionHealth: "Retention health · FSRS forecast",
    questionEcho: "The card",
    flipHint: "pick one — the card turns",
    gradeHint: "keys 1–4",
    confHint: "keys 1–3",
    asideKey: "E",
    cardOf: (i: number, n: number) => `Card ${i} of ${n}`,
    deckLeft: (n: number) => `${n} left in the deck`,
    fsrsNote:
      "FSRS predicts recall per card and surfaces each at its optimal spacing — not fixed SM-2 steps.",
  },
  "pt-BR": {
    map: "← Mapa",
    thisNode: "Este nó",
    retainReview: "Retain · Revisão",
    doneForToday: "Terminado por hoje",
    queueClear: "Fila zerada. Você terminou num nó verde.",
    finishedBody:
      "Curto, vencível, e acendeu alguma coisa — a sensação que te traz de volta amanhã. O FSRS já agendou cada card para seu próximo momento ideal.",
    litUpToday: (labels: string) => `Acendeu hoje · ${labels}`,
    dayStreak: "dias seguidos",
    todayIn: "hoje, dominados",
    nodesAlive: "nós vivos",
    freezesBanked: (n: number) =>
      `${n} congelamento${n === 1 ? "" : "s"} guardado${n === 1 ? "" : "s"} — perder um dia não quebra a sequência.`,
    backToMap: "Voltar ao mapa →",
    autoGenerated: (source: string) =>
      `gerado automaticamente · da sua sessão de ${source}`,
    beforeFlip: "Antes de virar · o quanto isso está sólido?",
    answer: "Resposta",
    explainAside: "Explicar · aparte Socrático rápido",
    gradeInterval: "Nota · define o próximo intervalo (FSRS)",
    confidenceVsResult: "Confiança vs. resultado",
    failedReexplainLead:
      "Um card que falha não só reagenda — uma reexplicação Socrática de 30 segundos, bem aqui:",
    nodeFlaggedShaky: (nodeLabel: string) =>
      `“${nodeLabel}” foi marcado como Instável no seu mapa.`,
    retentionFailureBody:
      "Uma falha de retenção reentra no ciclo — o nó volta a puxar atenção até ser reensinado. É isso que separa o app de um Anki com chatbot.",
    reteachNow: "Reensinar agora →",
    scheduleReteach: "Agendar reensino · continuar",
    todaysBudget: "Orçamento de hoje",
    dailyTarget: (min: number) => `Meta diária · ${min} min`,
    budgetBody:
      "Pensado em minutos, nunca uma parede de cards. Quando a meta é cumprida, você terminou — sem culpa.",
    retentionHealth: "Saúde da retenção · previsão FSRS",
    questionEcho: "O card",
    flipHint: "escolha uma — o card vira",
    gradeHint: "teclas 1–4",
    confHint: "teclas 1–3",
    asideKey: "E",
    cardOf: (i: number, n: number) => `Card ${i} de ${n}`,
    deckLeft: (n: number) => `${n} restantes no baralho`,
    fsrsNote:
      "O FSRS prevê a lembrança de cada card e o mostra no seu espaçamento ideal — não em passos fixos do SM-2.",
  },
} as const;
