// The seed concept map, diagnostic script, and mastery-state vocabulary.
// In the final product this graph is generated by the AI from a grounded
// source; the onboarding flow ships with the Linear Algebra demo map from
// the design so the "watch the territory assemble" moment is real.

export type NodeState =
  | "unknown"
  | "frontier"
  | "learning"
  | "shaky"
  | "mastered"
  | "gap";

/**
 * A node's stored progress. `frontier` is never stored — it is derived:
 * an `unknown` node whose prerequisites have all been learned displays as
 * frontier, otherwise it displays as locked-unknown.
 */
export type ProgressState = Exclude<NodeState, "frontier">;

export interface ConceptNode {
  id: string;
  label: string;
  /** Seed progress state for the demo map (see `initialStates`). */
  state: ProgressState;
  /** Generation (topological depth) — controls staged reveal during the diagnostic. */
  g: number;
  /** Week the node first lit up (0 = placement diagnostic) — drives the momentum replay. */
  week: number;
  x: number;
  y: number;
  gap?: boolean;
}

/** [from, to, dashed?] — direction is prerequisite → dependent. */
export type ConceptEdge = readonly [string, string, boolean?];

/**
 * The live graph. Re-planning (Phase 1) restructures it — spawning gap
 * sub-nodes from failures — so the app holds it as state seeded from
 * `NODES`/`EDGES`, never the module constants directly.
 */
export interface ConceptGraph {
  nodes: ConceptNode[];
  edges: ConceptEdge[];
}

export function seedGraph(): ConceptGraph {
  return { nodes: [...NODES], edges: [...EDGES] };
}

export const NODES: ConceptNode[] = [
  { id: "vec", label: "Vectors", state: "mastered", g: 1, week: 0, x: 110, y: 400 },
  { id: "vecops", label: "Vector Operations", state: "mastered", g: 1, week: 0, x: 320, y: 250 },
  { id: "matrices", label: "Matrices", state: "mastered", g: 1, week: 0, x: 320, y: 520 },
  { id: "systems", label: "Linear Systems", state: "mastered", g: 1, week: 0, x: 320, y: 720 },
  { id: "lincomb", label: "Linear Combinations", state: "mastered", g: 2, week: 0, x: 560, y: 180 },
  { id: "matmul", label: "Matrix Multiplication", state: "learning", g: 2, week: 3, x: 560, y: 430 },
  { id: "gauss", label: "Gaussian Elimination", state: "shaky", g: 2, week: 1, x: 560, y: 700 },
  { id: "span", label: "Span", state: "mastered", g: 2, week: 0, x: 800, y: 160 },
  { id: "lintrans", label: "Linear Transformations", state: "unknown", g: 3, week: 4, x: 820, y: 420 },
  { id: "det", label: "Determinants", state: "unknown", g: 3, week: 4, x: 820, y: 670 },
  { id: "linind", label: "Linear Independence", state: "shaky", g: 3, week: 2, x: 1055, y: 150 },
  { id: "gap1", label: "Base-case independence", state: "gap", g: 3, week: 2, x: 975, y: 295, gap: true },
  { id: "rank", label: "Rank & Nullspace", state: "unknown", g: 3, week: 4, x: 1065, y: 470 },
  { id: "inverse", label: "Inverse Matrices", state: "unknown", g: 3, week: 4, x: 1065, y: 695 },
  { id: "basis", label: "Basis", state: "unknown", g: 3, week: 4, x: 1310, y: 180 },
  { id: "eigval", label: "Eigenvalues", state: "unknown", g: 3, week: 4, x: 1340, y: 445 },
  { id: "eigvec", label: "Eigenvectors", state: "unknown", g: 3, week: 4, x: 1570, y: 345 },
  { id: "diag", label: "Diagonalization", state: "unknown", g: 3, week: 4, x: 1795, y: 345 },
];

export const EDGES: ConceptEdge[] = [
  ["vec", "vecops"],
  ["vec", "matrices"],
  ["vec", "systems"],
  ["vecops", "lincomb"],
  ["vecops", "matmul"],
  ["matrices", "matmul"],
  ["systems", "gauss"],
  ["matrices", "gauss"],
  ["lincomb", "span"],
  ["matmul", "lintrans"],
  ["matrices", "lintrans"],
  ["matrices", "det"],
  ["gauss", "det"],
  ["span", "linind"],
  ["lincomb", "linind"],
  ["lintrans", "rank"],
  ["matmul", "rank"],
  ["det", "inverse"],
  ["gauss", "inverse"],
  ["linind", "basis"],
  ["span", "basis"],
  ["basis", "eigval"],
  ["det", "eigval"],
  ["lintrans", "eigval"],
  ["eigval", "eigvec"],
  ["basis", "eigvec"],
  ["eigvec", "diag"],
  ["inverse", "diag"],
  ["linind", "gap1", true],
];

export const STATE_COLOR: Record<NodeState, string> = {
  unknown: "#b3ada2",
  frontier: "#c99a2e",
  learning: "#5b7fbf",
  shaky: "#bd7038",
  mastered: "#4c8b63",
  gap: "#c1574a",
};

export const STATE_LABEL: Record<NodeState, string> = {
  unknown: "Unknown",
  frontier: "Frontier · ready",
  learning: "Learning",
  shaky: "Shaky",
  mastered: "Mastered",
  gap: "Gap",
};

/** Calibration/metacognition copy shown in the node detail rail per state. */
export const STATE_CONFIDENCE: Record<NodeState, string> = {
  mastered:
    "Understood, retained, and applied in a novel context. This is real mastery — keep it alive in Review.",
  frontier:
    "Prerequisites met. This is your edge — the right place to start. Begin with a short Consume pass.",
  learning:
    "Understanding is forming. Teach it back next to surface the parts you're still hand-waving.",
  shaky:
    "You feel solid here, but your last application failed. That's fluency, not mastery — re-attempt the Crucible.",
  unknown:
    "Locked. Clear the prerequisites below and this lights up on your frontier.",
  gap: "Spawned from a detected failure. A targeted Socratic pass closes just this sub-point.",
};

export const PHASES = [
  "Consume",
  "Socratic",
  "Feynman",
  "Connect",
  "Crucible",
  "Retained",
] as const;

export type Phase = (typeof PHASES)[number];

/**
 * The gentle skip flag: what's still unfinished when the learner jumps past
 * the recommended next phase. Keyed by the phase being skipped over.
 */
export const PHASE_SKIP_NUDGE: Record<Phase, string> = {
  Consume: "You haven't read this yet — want to?",
  Socratic: "You haven't reasoned this out yet — want to?",
  Feynman: "You haven't taught this back yet — want to?",
  Connect: "You haven't linked this into your map yet — want to?",
  Crucible: "You haven't applied this in a novel context yet — want to?",
  Retained: "This isn't in your review rotation yet — want to?",
};

/** Which phase a node is on, given its mastery state (-1 = locked). */
export function phaseIndex(state: NodeState): number {
  switch (state) {
    case "frontier":
      return 0;
    case "learning":
      return 2;
    case "shaky":
      return 4;
    case "mastered":
      return 6;
    default:
      return -1;
  }
}

export interface DiagnosticQuestion {
  tag: string;
  q: string;
  note: string;
  opts: string[];
}

export const DIAGNOSTIC: DiagnosticQuestion[] = [
  {
    tag: "Question 1 of 3",
    q: "Given two vectors, can you compute their dot product by hand?",
    note: "A confident yes prunes the entire arithmetic branch — we won't re-teach it.",
    opts: ["Yes, easily", "Roughly", "No"],
  },
  {
    tag: "Question 2 of 3",
    q: "Solve a 2×2 system by Gaussian elimination without notes?",
    note: "You hesitated on back-substitution earlier — we'll mark elimination shaky, not done.",
    opts: ["Yes", "With hints", "Not yet"],
  },
  {
    tag: "Question 3 of 3",
    q: "In one sentence: what makes a set of vectors a basis?",
    note: "This pins your frontier. Independence + basis light up as your edge.",
    opts: ["Spans & independent", "Something about spanning?", "Not sure"],
  },
];

export type GoalKind = "exam" | "project" | "mastery";

export const GOALS: ReadonlyArray<[GoalKind, string]> = [
  ["exam", "Pass an exam"],
  ["project", "Build a project"],
  ["mastery", "General mastery"],
];

export const DAILY_TARGETS = [10, 15, 20, 30] as const;

export interface OnboardingForm {
  topic: string;
  goal: GoalKind;
  interests: string;
  target: number;
}

export const DEFAULT_FORM: OnboardingForm = {
  topic: "Linear Algebra",
  goal: "exam",
  interests: "chess, investing",
  target: 15,
};

/** Every ancestor of `id` (including itself) along prerequisite edges. */
export function ancestorsOf(id: string, edges: ConceptEdge[]): Set<string> {
  const rev: Record<string, string[]> = {};
  for (const [a, b] of edges) (rev[b] = rev[b] ?? []).push(a);
  const seen = new Set([id]);
  const stack = [id];
  while (stack.length) {
    const cur = stack.pop()!;
    for (const p of rev[cur] ?? []) {
      if (!seen.has(p)) {
        seen.add(p);
        stack.push(p);
      }
    }
  }
  return seen;
}

/** Every descendant of `id` (excluding itself) along solid prerequisite edges. */
export function descendantsOf(id: string, edges: ConceptEdge[]): Set<string> {
  const fwd: Record<string, string[]> = {};
  for (const [a, b, dashed] of edges) {
    if (!dashed) (fwd[a] = fwd[a] ?? []).push(b);
  }
  const seen = new Set<string>();
  const stack = [id];
  while (stack.length) {
    const cur = stack.pop()!;
    for (const d of fwd[cur] ?? []) {
      if (!seen.has(d)) {
        seen.add(d);
        stack.push(d);
      }
    }
  }
  return seen;
}

// ---- live mastery state ----------------------------------------------------
// The app holds one `Record<node id, ProgressState>`; every surface reads it
// and every phase writes it back. Frontier and locking are derived, never set.

export type StateMap = Record<string, ProgressState>;

export function initialStates(): StateMap {
  return Object.fromEntries(NODES.map((n) => [n.id, n.state]));
}

/** A prerequisite is met once the node has been learned at least once. */
function isLearned(state: ProgressState | undefined): boolean {
  return state === "learning" || state === "shaky" || state === "mastered";
}

/** Solid prerequisite edges into each node (dashed gap edges don't lock). */
function prereqMap(edges: ConceptEdge[]): Record<string, string[]> {
  const prereqs: Record<string, string[]> = {};
  for (const [from, to, dashed] of edges) {
    if (!dashed) (prereqs[to] = prereqs[to] ?? []).push(from);
  }
  return prereqs;
}

/**
 * What each node shows on the map: stored progress, except that an `unknown`
 * node with every prerequisite learned lights up as `frontier` (the ZPD).
 * A node left `unknown` here is locked by definition.
 */
export function displayStates(
  states: StateMap,
  graph: ConceptGraph,
): Record<string, NodeState> {
  const prereqs = prereqMap(graph.edges);
  const out: Record<string, NodeState> = {};
  for (const node of graph.nodes) {
    const state = states[node.id] ?? "unknown";
    // Gap nodes never join the frontier — they hang off their parent via a
    // dashed edge and are entered from its detail rail, not unlocked.
    out[node.id] =
      state === "unknown" &&
      !node.gap &&
      (prereqs[node.id] ?? []).every((p) => isLearned(states[p]))
        ? "frontier"
        : state;
  }
  return out;
}

/**
 * Why a node is locked: its unlearned ancestors (plus the node itself),
 * i.e. the "learn these first" path highlighted on the map.
 */
export function unmetPathOf(
  id: string,
  states: StateMap,
  graph: ConceptGraph,
): Set<string> {
  const path = new Set<string>();
  for (const anc of ancestorsOf(id, graph.edges)) {
    if (anc === id || !isLearned(states[anc])) path.add(anc);
  }
  return path;
}

// ---- Phase 1 · Plan (the re-planning behavior of the map) ------------------
// Not a screen: the map continuously reorders to the goal, warns about pace,
// prunes diagnosed-known material, and spawns gap sub-nodes from failures.
// The only recurring UI is the "Map updated" toast when it restructures.

/** Goal-conditioned frontier ordering: which lit node to attack, and why. */
export interface PlanEntry {
  node: ConceptNode;
  /** How many not-yet-learned concepts this node transitively unlocks. */
  unlocks: number;
}

export const GOAL_ORDER_CAPTION: Record<GoalKind, string> = {
  exam: "ordered to your exam — highest leverage first",
  project: "ordered to your build — unlocks the tools first",
  mastery: "foundations first — depth over speed",
};

/**
 * The plan itself: frontier nodes ordered to the goal. A deadline-driven
 * goal attacks the nodes that unlock the most remaining territory; general
 * mastery walks foundations-to-frontier.
 */
export function orderedFrontier(
  display: Record<string, NodeState>,
  graph: ConceptGraph,
  goal: GoalKind,
): PlanEntry[] {
  const entries: PlanEntry[] = graph.nodes
    .filter((n) => display[n.id] === "frontier")
    .map((node) => ({
      node,
      unlocks: [...descendantsOf(node.id, graph.edges)].filter((d) => {
        const s = display[d];
        return s === "unknown" || s === "frontier";
      }).length,
    }));
  entries.sort((a, b) =>
    goal === "mastery"
      ? a.node.x - b.node.x
      : b.unlocks - a.unlocks || a.node.x - b.node.x,
  );
  return entries;
}

/** Days until the demo exam deadline (the left-rail countdown chip). */
export const EXAM_DAYS = 24;
/** Rough minutes of focused work to take one concept through the spiral. */
export const NODE_MINUTES = 35;

export interface PaceStatus {
  /** Non-gap concepts not yet mastered. */
  remaining: number;
  daysLeft: number;
  /** Minutes/day the remaining territory demands before the deadline. */
  neededPerDay: number;
  /** The learner's daily target from onboarding. */
  targetPerDay: number;
  onTrack: boolean;
}

/** Pace against the deadline — the map's warning when it won't make it. */
export function paceStatus(
  states: StateMap,
  graph: ConceptGraph,
  targetPerDay: number,
): PaceStatus {
  const remaining = graph.nodes.filter(
    (n) => !n.gap && states[n.id] !== "mastered",
  ).length;
  const neededPerDay = Math.ceil((remaining * NODE_MINUTES) / EXAM_DAYS);
  return {
    remaining,
    daysLeft: EXAM_DAYS,
    neededPerDay,
    targetPerDay,
    onTrack: neededPerDay <= targetPerDay,
  };
}

/** A sub-concept the re-planner can spawn under a node when it keeps failing. */
export interface GapSpec {
  id: string;
  label: string;
  /** Why the AI split it out — quoted in the "Map updated" toast. */
  reason: string;
  /** Placement offset from the parent node. */
  dx: number;
  dy: number;
}

/**
 * What a failure under each node splits into, in order. Each failed
 * application (or diagnostic hesitation) spawns the next unspawned spec;
 * when the list is exhausted the re-attempt is allowed to succeed.
 */
export const FAILURE_GAPS: Record<string, GapSpec[]> = {
  gauss: [
    {
      id: "gap-backsub",
      label: "Back-substitution",
      reason: "you hesitated walking back up the rows in the diagnostic",
      dx: -85,
      dy: 148,
    },
    {
      id: "gap-pivot",
      label: "Pivot bookkeeping",
      reason: "row swaps keep scrambling your signs",
      dx: 130,
      dy: 138,
    },
  ],
  linind: [
    {
      id: "gap-zerovec",
      label: "Zero-vector traps",
      reason: "the zero vector keeps slipping through your independence checks",
      dx: 140,
      dy: 120,
    },
  ],
};

/** Nodes spawned mid-map belong to the current (post-replay) week. */
const SPAWN_WEEK = 4;

/** The next sub-concept a failure under `parentId` would split out, if any. */
export function nextGapFor(
  graph: ConceptGraph,
  parentId: string,
): GapSpec | null {
  const specs = FAILURE_GAPS[parentId] ?? [];
  return specs.find((s) => graph.nodes.every((n) => n.id !== s.id)) ?? null;
}

/**
 * The restructure itself: a new red gap node hung under its parent by a
 * dashed edge. Idempotent — an already-spawned spec returns the graph as-is.
 */
export function spawnGap(
  graph: ConceptGraph,
  parentId: string,
  spec: GapSpec,
): ConceptGraph {
  const parent = graph.nodes.find((n) => n.id === parentId);
  if (!parent || graph.nodes.some((n) => n.id === spec.id)) return graph;
  const node: ConceptNode = {
    id: spec.id,
    label: spec.label,
    state: "gap",
    g: parent.g,
    week: SPAWN_WEEK,
    x: parent.x + spec.dx,
    y: parent.y + spec.dy,
    gap: true,
  };
  return {
    nodes: [...graph.nodes, node],
    edges: [...graph.edges, [parentId, spec.id, true]],
  };
}
